name: Publish UPM packages
on:
  release:
    types: [published]
  workflow_dispatch:
env:
  # Dry-run on workflow_dispatch
  NPM_OPTS: ${{ github.event_name == 'workflow_dispatch' && '--dry-run --tag canary' || '' }}
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: actions/setup-node@v5
      with:
        node-version: 'latest'
        registry-url: 'https://registry.npmjs.org'
    # Publish NPM using OIDC token
    - run: npm install -g npm@latest
    - run: npm publish ${{ env.NPM_OPTS }}
      working-directory: Packages/com.github.asus4.tflite
    - run: npm publish ${{ env.NPM_OPTS }}
      working-directory: Packages/com.github.asus4.tflite.common
    - run: npm publish ${{ env.NPM_OPTS }}
      working-directory: Packages/com.github.asus4.mediapipe
